apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellotom
  name: hellotom
  namespace: tomasz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellotom
  template:
    metadata:
      labels:
        app: hellotom
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: primary
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

